# 개발용 도커컴포즈

version: "3"

services:
  rest-server:
    container_name: rest-server
    build:
      context: .
      dockerfile: ./apps/rest-server/Dockerfile
    restart: always
    ports:
      - 8080:8080

  game-server:
    container_name: game-server
    build:
      context: .
      dockerfile: ./apps/game-server/Dockerfile
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - rest-server

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - rest-server
      - game-server
