# 개발용 도커컴포즈

version: "3"

services:
  rest-server:
    container_name: rest-server
    build:
      context: .
      dockerfile: ./apps/rest-server/Dockerfile.dev
    restart: always
    ports:
      - 8080:8080

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.dev
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - rest-server
