# 개발용 도커컴포즈

version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000

  about:
    container_name: about
    build:
      context: .
      dockerfile: ./apps/about/Dockerfile
    restart: always
    ports:
      - 3001:3001
