# Workflow name
name: "Chromatic Deployment"

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic:
    name: "Run Chromatic"
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Install dependencies"
        run: yarn

        #👇 Adds Chromatic as a step in the workflow
      - name: Publish Chromatic
        uses: chromaui/action@latest
        # Options required for Chromatic's GitHub Action
        with:
          workingDir: apps/storybook
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/ko/deploy/ to obtain it
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
