name: Docker Build & Deploy

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 실행

jobs:
  build_and_push:
    runs-on: ubuntu-22.04-arm

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: rest-server Docker 이미지 빌드 & 푸시
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/puzzlepop2:rest-server -f apps/rest-server/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/puzzlepop2:rest-server

      - name: web Docker 이미지 빌드 & 푸시
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/puzzlepop2:web -f apps/web/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/puzzlepop2:web

  deploy:
    runs-on: ubuntu-22.04-arm
    needs: build_and_push

    steps:
      - name: Deploy to Oracle Cloud VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/puzzlepop2

            echo "Stopping running containers..."
            docker-compose down

            echo "Removing old images..."
            docker rmi ${{ secrets.DOCKER_USERNAME }}/puzzlepop2:rest-server
            docker rmi ${{ secrets.DOCKER_USERNAME }}/puzzlepop2:web

            echo "Starting containers..."
            docker-compose up -d --remove-orphans

            echo "Cleaning up unused images..."
            docker image prune -f
