name: Docker Build & Deploy

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 실행

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: rest-server Docker 이미지 빌드 & 푸시
        run: |
          docker build -t ryong9rrr/puzzlepop2:rest-server -f apps/rest-server/Dockerfile .
          docker push ryong9rrr/puzzlepop2:rest-server

      - name: web Docker 이미지 빌드 & 푸시
        run: |
          docker build -t ryong9rrr/puzzlepop2:web -f apps/web/Dockerfile .
          docker push ryong9rrr/puzzlepop2:web
